import test from 'node:test';import assert from 'node:assert/strict';import {randomUUID} from 'node:crypto';
import {applyAuditWrite} from '../audit/audit-permissions.mjs';import {normalizeAuditEntry} from '../audit/audit-store.mjs';import {prepareMobileWrite} from '../audit/mobile-sync.mjs';
const actor={userId:'owner',email:'owner@example.test',respond:true};
const entry={id:'finding',projectId:'p',finding:'Finding',actions:[{id:'action',description:'Fix',owner:'owner',email:actor.email,status:'Open',responses:[]}]};
const image={name:'proof.png',dataUrl:'data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAAEAAAABCAQAAAC1HAwCAAAAC0lEQVR42mP8/x8AAwMCAO+jRZkAAAAASUVORK5CYII='};
const patch={id:entry.id,operation:'reply',actionId:'action',text:'Work completed',status:'Closed',images:[image],author:'spoof',createdAt:'2000-01-01T00:00:00.000Z'};
test('action updates preserve evidence/status and trust server author/time only',()=>{const before=Date.now();const saved=normalizeAuditEntry(applyAuditWrite(actor,patch,entry));const r=saved.actions[0].responses[0];assert.equal(r.author,'owner');assert(Date.parse(r.createdAt)>=before);assert.equal(r.status,'Closed');assert.deepEqual(r.images[0],{...image,url:'',description:''});assert.equal(entry.actions[0].responses.length,0);});
test('unassigned callers and malformed/excess photos are rejected',()=>{assert.throws(()=>applyAuditWrite({...actor,email:'other@example.test'},patch,entry),{statusCode:403});for(const images of [Array(9).fill(image),[{url:'/audit/uploads/other-user.png'}],[{dataUrl:'data:text/html;base64,AA=='}]])assert.throws(()=>applyAuditWrite(actor,{...patch,images},entry),{statusCode:400});});
test('offline photo retry preserves one update and its evidence',()=>{const op={operationId:randomUUID(),base:{status:'Open',responseDueDate:''},patch};const saved=normalizeAuditEntry(prepareMobileWrite(actor,op,entry).entry);const retry=prepareMobileWrite(actor,op,saved);assert(retry.duplicate);assert.equal(retry.entry.actions[0].responses.length,1);assert.equal(retry.entry.actions[0].responses[0].images.length,1);});
