// Run only against the isolated mobile test fixture, never production.
const {chromium}=await import(process.env.PLAYWRIGHT_MODULE || 'playwright');
import assert from 'node:assert/strict';
const browser=await chromium.launch({channel:'chrome',headless:true});
const context=await browser.newContext({viewport:{width:390,height:844},isMobile:true,hasTouch:true});
const page=await context.newPage();const errors=[];page.on('pageerror',e=>errors.push(e.message));
const findingTitle='Offline drainage finding '+Date.now();
const base=process.env.MOBILE_TEST_URL || 'http://127.0.0.1:4187',api='/api/projects/project_opsl_15000ha_development/';
const login=async(name)=>{await page.goto(base+'/mobile-app/index.html');await page.locator('[name=userid]').fill(name);await page.locator('[name=password]').fill('MobileTest-Only-2026');await page.locator('#login button').click();await page.getByRole('heading',{name:'Make every action count.'}).waitFor();await page.waitForFunction(()=>!document.querySelector('.top button')?.textContent.includes('Syncing'));};
await login('mobile.milo');
assert.ok([403,404].includes((await context.request.get(base+'/api/projects')).status()));
await page.screenshot({path:(process.env.MOBILE_TEST_OUTPUT || '/tmp')+'/mobile-overview.png',fullPage:true});
await page.evaluate(()=>navigator.serviceWorker.ready);
await context.setOffline(true);
await page.reload();await page.getByRole('heading',{name:'Make every action count.'}).waitFor();
await page.locator('.bottom [data-nav=capture]').click();
await page.locator('[name=department]').fill('Mobile test');await page.locator('[name=finding]').fill(findingTitle);await page.locator('[name=impact]').fill('Access blocked after rainfall.');await page.locator('[name=location]').fill('Block 12');
await page.locator('#images').setInputFiles({name:'evidence.png',mimeType:'image/png',buffer:Buffer.from('iVBORw0KGgoAAAANSUhEUgAAAAEAAAABCAQAAAC1HAwCAAAAC0lEQVR42mP8/x8AAwMCAO+jRZkAAAAASUVORK5CYII=','base64')});
await page.waitForFunction(()=>document.querySelector('#draftPhotos img'));
await page.reload();await page.locator('.bottom [data-nav=capture]').click();assert.equal(await page.locator('[name=finding]').inputValue(),findingTitle);assert.equal(await page.locator('#draftPhotos img').count(),1);
await page.locator('#finding button.primary').click();await page.getByRole('heading',{name:findingTitle,exact:true}).waitFor();
await page.locator('[data-do=add-action]').click();await page.locator('[name=description]').fill('Clear the channel');
assert.equal(await page.locator('#assignee option').count(),3);
await page.locator('#assignee').selectOption('mobile.milo');assert.equal(await page.locator('[name=email]').inputValue(),'milo@example.test');assert.equal(await page.locator('[name=email]').getAttribute('readonly'),'');
await page.locator('[name=dueDate]').fill('2026-10-20');await page.locator('#action button').click();
await page.locator('[data-reply]').click();await page.locator('[name=text]').fill('Work started offline');await page.locator('[name=status]').selectOption('In progress');await page.locator('[name=dueDate]').fill('2026-10-21');await page.locator('#reply button').click();
await page.screenshot({path:(process.env.MOBILE_TEST_OUTPUT || '/tmp')+'/mobile-detail-offline.png',fullPage:true});
await page.locator('.bottom [data-nav=sync]').click();assert.equal(await page.locator('.stack .card').count(),3);
await context.setOffline(false);await page.waitForFunction(()=>document.querySelector('.empty')?.textContent.includes('All saved changes are synced'),{timeout:60000});
const response=await context.request.get(base+api+'audit-entries?q='+encodeURIComponent(findingTitle));const data=await response.json();assert.equal(data.total,1);const entry=data.items[0];assert.equal(entry.actions.length,1);assert.equal(entry.actions[0].responses.length,1);assert.equal(entry.actions[0].status,'In progress');assert.equal(entry.observationImages.length,1);assert.ok(entry.observationImages[0].url);assert.equal((await context.request.get(base+entry.observationImages[0].url)).status(),200);
const direct={operationId:crypto.randomUUID(),patch:{id:entry.id,operation:'reply',actionId:entry.actions[0].id,text:'Retry safe',status:'In progress',dueDate:'2026-10-21'},base:{status:'In progress',responseDueDate:'2026-10-21'}};
const first=await context.request.post(base+api+'audit-sync',{data:direct}),second=await context.request.post(base+api+'audit-sync',{data:direct});assert.equal(first.status(),200);assert.equal((await second.json()).entry.actions[0].responses.length,2);
const bad=await context.request.post(base+api+'audit-sync',{data:{operationId:crypto.randomUUID(),patch:{id:entry.id,operation:'add-action',action:{description:'Bad assignment',owner:'admin',email:'admin@example.test',dueDate:'2026-10-20'}}}});assert.equal(bad.status(),400);
await page.locator('.bottom [data-nav=account]').click();await page.waitForFunction(()=>!document.querySelector('.top button')?.textContent.includes('Syncing'));await page.locator('[data-do=logout]').click();await page.locator('[name=userid]').waitFor();await login('mobile.owner');assert.equal(await page.locator('.bottom [data-nav=capture]').count(),0);await page.locator('.bottom [data-nav=audits]').click();await page.locator('#search').fill(findingTitle);await page.locator('[data-open]').click();assert.equal(await page.locator('[data-do=add-action]').count(),0);assert.equal(await page.locator('[data-reply]').count(),0);
await page.screenshot({path:(process.env.MOBILE_TEST_OUTPUT || '/tmp')+'/mobile-respondent.png',fullPage:true});
assert.equal(await page.evaluate(()=>document.documentElement.scrollWidth>innerWidth),false);assert.deepEqual(errors,[]);
console.log('PASS: online login, offline reload, persisted photo/draft, dependent create/action/reply sync, idempotent retries, directory email, API isolation and respondent controls.');
await browser.close();
